[package]
name = "gurt"
version = "0.1.0"
edition = "2021"
authors = ["FaceDev"]
license = "MIT"
repository = "https://github.com/outpoot/gurted"
description = "Official GURT:// protocol implementation"

[lib]
name = "gurt"
crate-type = ["cdylib", "lib"]

[dependencies]
tokio = { version = "1.0", features = [
    "net",
    "io-util", 
    "rt",
    "macros",
    "rt-multi-thread",
    "time",
    "fs"
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tracing = "0.1"
chrono = { version = "0.4", features = ["serde"] }

tokio-rustls = "0.26"
rustls = "0.23"
rustls-pemfile = "2.0"
rustls-native-certs = "0.8"
base64 = "0.22"
url = "2.5"

[dev-dependencies]
tokio-test = "0.4"
tracing-subscriber = "0.3"
sha2 = "0.10"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true